Repository yeiyei09/hospital, pull requests merged in 2025-08, with the labels that each got.

#1 feature: creacion de la conexion a la base de datos, creacion de los …
  crud.py
  database.py
  main.py
  models.py
  schemas.py
Labels: enhancement

#2 Fix: tipo de dato idPaciente
  crud.py
  database.py
  main.py
  models.py
  schemas.py
Labels: bug

#4 feat: crecion de main y crud pacientes
  crud.py
  database.py
  main.py
Labels: enhancement

#6 Feature andres
  crud.py
  database.py
  main.py
Labels: enhancement

#8 Feature andres
  crud.py
  main.py
  schemas.py
Labels: bug

#9 fix: Error 500 en las personas, por tipo de dato.
  crud.py
  main.py
  models.py
  schemas.py
Labels: bug

#11 Feat: cambio de crud en enfermeras y medicos
  database.py
  main.py
Labels: enhancement

#15 Feature andres
  crud.py
  database.py
  main.py
  models.py
  schemas.py
Labels: bug

#17 Feature andres
  crud.py
  database.py
  main.py
  models.py
  schemas.py
Labels: duplicate

#20 feat: creacion de query paramether en enfermeras.
  crud.py
  main.py
Labels: enhancement

#22 Feature andres
  README.md
  crud.py
  main.py
Labels: enhancement

#23 Feature andres
  README.md
  main.py
  schemas.py
Labels: enhancement
